- name: Pull new Docker image from registry and deploy
  hosts: all

  tasks:
    - name: Sign in to Docker Hub
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Pull new Docker image from registry
      shell:
        cmd: docker pull spheredrex/crazy-people-who-code-after-work:network-manager-gui

    - name: Stop the running instance of the Docker image
      shell:
        cmd: docker stop $(docker ps -q --filter ancestor=spheredrex/crazy-people-who-code-after-work:network-manager-gui)
      ignore_errors: yes

    - name: Run the new image
      shell:
        cmd: docker run -p 5173:5173 -d spheredrex/crazy-people-who-code-after-work:network-manager-gui